### ISSUE TITLE
TEPs-I 2019 Outputs for EED

### ISSUE THREAD

**Issue by cczhu** [CityofToronto/bdit_traffic_prophet#47]
Environment & Energy Division (EED) requests 2019 data to complete their GHG inventory.

Follow the process documented in #41.

Tasks:
- [x] Generate 15-minute count bin zips for 2019. I'm pretty sure the notebook we created back in February tests both of the issues below.
  - [x] Since we're restricted to information TEPs has on locations, determine which centreline IDs exist in TEPs PRTCS and KCOUNT data (this includes `PRTCS/negative/mid_f_point.csv` and `Landuse_pop_lane_speed.xlsx`).
  - [x] Determine if there's any conflict between centreline IDs assigned to HW401 data and in our data.
- [x] Confirm TEPs can be successfully run using new data.
- [x] Run TEPs using all available data for years of analysis 2019.
- [x] Compare output of run against the 2017-2018 only output of #41.

**Comment by cczhu** [comment]
## Relevant notebooks

[Convert Postgres data to zips for TEPS](https://github.com/CityofToronto/bdit_traffic_prophet/tree/sandbox/sandbox/20200204_zips_for_teps)

[TEPs output analysis](https://github.com/CityofToronto/bdit_traffic_prophet/blob/sandbox/sandbox/20200218-tepsrerunwithnewdata/TEPs%20Output%20Analysis.ipynb)

## Relevant e-mails

**From myself 2020-02-14**

> We're testing if we can generate AADT estimates for 2017-2018 by feeding in new short term and permanent counts into TEPs-I.  As part of this, I'm also hoping to determine which files inside of the Emission folder are needed for TEPs-II, and which files were only used by Arman for testing.

> I've generated a preliminary dataset of AADT estimates for EED.  These numbers are not final, as we're still QCing the results, but I was hoping we could test the data handover process with you to make sure we know exactly which files we need to send in the future.  Would you be willing to help us to run TEPs-II on the dataset? The files are large, and I can either upload them to Google Drive or use the secure FTP system you used to send TEPs-II to me.  If you prefer the latter, do you know how I can sign up for that service and upload files?

**From Sean Severin 2020-02-24**

(After some back and forth with me to confirm the validity of his VKT numbers.

> I've just finished re-running and summing the data from the model run after deleting all the old stuff, and the numbers have not changed.  

## Local paths

TEPs-I:
`/mnt/c/Users/czhu5/Documents/VolumeModel/TEPs-I-EEDrun/`

**Comment by cczhu** [comment]
Aakash refreshed `prj_volume.centreline_volumes` on 2020-12-14. I forgot that we're reading from `czhu.btp_centreline_volumes`, so I refreshed `prj_volume.centreline_volumes`.

**Comment by cczhu** [comment]
Problem: `prj_volume.centreline_volumes` contains both ATR and TMC counts - the former is `count_type = 1` and the latter `2`. TMC counts aren't 24 hour counts, and neither Traffic Prophet nor TEPs have controls that ensure they're rejected by the count matching algorithm. We should remove them from the zip-making procedure.

Trouble is they were included back in March for the 2017 and 2018 zips.

New strategy:
- Generate and validate count zips for 2017-2019.
- Run TEPs to predict 2017-2019. Compare 2017-2018 with previous predictions.

**Comment by cczhu** [comment]
Running TEPs-I for 2017 with the following settings (which should be identical to [this post](https://github.com/CityofToronto/bdit_traffic_prophet/issues/41#issuecomment-584245635):

![image](https://user-images.githubusercontent.com/442891/102544120-54595980-4082-11eb-9fbf-255a8a14a409.png)

The working directory here is `Documents\VolumeModel\TEPS-I-EEDrun\`

I pressed `Estimate AADTs`. I'll press `Estimate Vehicle Speeds next, [following this comment](https://github.com/CityofToronto/bdit_traffic_prophet/issues/41#issuecomment-584701288)

Irritatingly I never bothered to document *which files are generated by this process*, so will have to do that later.

**Comment by cczhu** [comment]
All done!

![image](https://user-images.githubusercontent.com/442891/102785358-da6bed80-436b-11eb-80b8-4f7759eec726.png)

Now for speeds.

**Comment by cczhu** [comment]
Running with these settings:

![image](https://user-images.githubusercontent.com/442891/102787162-a0e8b180-436e-11eb-824c-9d0d762c4714.png)

**Comment by cczhu** [comment]
All done!

![image](https://user-images.githubusercontent.com/442891/102829714-b2a17780-43b5-11eb-9877-3a2a2421f76a.png)

**Comment by cczhu** [comment]
Zipped files for EED

![image](https://user-images.githubusercontent.com/442891/102829857-fe542100-43b5-11eb-9384-545355eea8e3.png)

**Comment by cczhu** [comment]
Running `TEPs Output Analysis.ipynb` (copied from `20200218-tepsrerunwithnewdata`) we can analyze the new "proposed" data against the older "baseline" run from February 2020. Recall this run erroneously includes 7.5 hour TMCs as short term counts in 2017-2018.

There are four tests included in `TEPs Output Analysis.ipynb`:

## Z-score test

This assumes that the value and lower and upper bounds given in the `final_aadt_{year}.csv` files coming out of TEPs represent estimates for the mean and twice the standard deviation at each centreline and year. The difference between the old and new estimates, then, should go like

![image](https://user-images.githubusercontent.com/442891/102938116-a5e65780-4479-11eb-9e0e-d9ee657bb201.png)

(That's a lot of assumptions, so this check needs to be taken with a grain of salt.)

In the following, we plot histograms of the z-score of the differences between proposed and baseline AADTs (orange bars). A standard normal (blue line) is also plotted for comparison. In the [past](https://github.com/CityofToronto/bdit_traffic_prophet/issues/41) the distributions have all been much more narrowly peaked than the standard normal, but now we get weird plots like this:

![image](https://user-images.githubusercontent.com/442891/102938307-12f9ed00-447a-11eb-922e-bde9a022f089.png)

I'm honestly not sure how to interpret this plot, but apparently I didn't place much faith in this check back in February either, since I never published any plots in the GitHub issue. So let's ignore this and go for a direct comparison between AADTs.

**Comment by cczhu** [comment]
## Absolute and Relative Difference

This is a plot of the proposed vs. the baseline data on a linear scale:

![image](https://user-images.githubusercontent.com/442891/102939210-d9c27c80-447b-11eb-980d-f17927decc0b.png)

We see two distributions - one that lands pretty closely to the y = x line (blue dashed), and a tail of outliers shallower than y = x close to the origin. Plotting the relative difference:

![image](https://user-images.githubusercontent.com/442891/102939240-e9da5c00-447b-11eb-824c-53d49ca51734.png)

errors at extremely large AADTs are typically at or below the 10% level while there's a tail of 100-1000% error for very small AADTs.  The shallow tail of outliers in the absolute plot can also be seen in the relative plot at around 30% relative error and < 0.5e5 baseline AADT.

**Comment by cczhu** [comment]
## Baseline vs. proposed map:

I also want to check that these errors are not geospatially clustered. We can do this by plotting the fractional deviation on a map for a given year:

![image](https://user-images.githubusercontent.com/442891/102939082-8d773c80-447b-11eb-93de-3077ed12e7dc.png)

I don't think there's any kind of visible spatial clustering here - instead, it looks like overall there is 10-20% error for AADT on minor roads, and closer to a few percent error on major roads.

The hope is these errors cancel each other out when summing up to the citywide VKT.

**Comment by cczhu** [comment]
## Citywide VKT estimate

And they do!

Here's a plot of the citywide VKT from both baseline and proposed data for all years in common:

![image](https://user-images.githubusercontent.com/442891/102939549-784edd80-447c-11eb-98d7-8d2226ad07c4.png)

![image](https://user-images.githubusercontent.com/442891/102939598-87ce2680-447c-11eb-87b3-97aeff98e7ff.png)

And here's their relative error:

![image](https://user-images.githubusercontent.com/442891/102939690-b64c0180-447c-11eb-864d-63190a014fe3.png)

The relative error between baseline and proposed is less than 1%. It's probably not worth it to care much further than this if the data is only to be used for a citywide estimate.

**Comment by cczhu** [comment]
Deleted all extraneous files from `Emission` following the format of `EED_20200214_minimalist.zip, and uploaded to Google Drive. Will close this issue upon successful delivery.

**Comment by aharpalaniTO** [comment]
Hi @cczhu - thanks for the detailed yet clear error checking here. I also have no clue how to interpret that z-score chart but the rest of it looked great. Love the maps as always. I'm going to send off.

A few other random comments / thoughts:
- some of the biggest changes in the baseline vs. proposed AADTs for 2016 (e.g Avenue Road S of Lawrence, Pharmacy Ave N of Sheppard) based on a spot check of a couple locations had recent counts along the corridor (i.e. latter half of 2018 or in 2019) where the ATR count had a difference of >5-10% relative to the most recent count before that based on scan of MOVE
- Would be interested in knowing if the change in VKT is directly proportional to change in CO2e (i.e. how sensitive is the model in the aggregate to speed) - question for EED
- we really should figure out how to make this process workable with the latest version of the centreline. Something to consider when working on traffic prophet

**Comment by cczhu** [comment]
Back in February (e-mail 2021-02-11) Sean discovered that there were >5% changes in the historical eCO2 estimates from TEPs-II using this most recent run of AADTs and speeds we sent him:

![image](https://user-images.githubusercontent.com/442891/112638560-c37ae280-8e15-11eb-9121-2d3be0ca0734.png)

Considering that the AADTs themselves change by < 1%, we suspected that this was a bug either in the speed estimation or emissions factor portions of TEPs. We contacted Arman for assistance. He discovered this to be because estimated AADTs had left the range of values the neural network was trained on, leading to spurious predictions highly sensitive to AADT (e-mail 2021-03-15). He addressed the issue by switching EMME-2011 simulation speed-volume data with EMME-2016 data, which he sent back to us (e-mail 2021-03-16).

To confirm that we can use Arman's updated data, running TEPs-I's speed estimate module only using the settings:

![image](https://user-images.githubusercontent.com/442891/112639420-9f6bd100-8e16-11eb-9658-0ab164c8bcc3.png)

**Comment by cczhu** [comment]
Made a remarkably stupid mistake and only ran 2006-2013 speeds, as seen above. Revised to 2006-2019:

![image](https://user-images.githubusercontent.com/442891/112844365-a8a4aa00-9071-11eb-977f-ffc521026a82.png)

**Comment by cczhu** [comment]
Run successfully completed, but TEPS crashed when zipping files.

Addendum - it worked, and it took an overly long time because it included the archive zip files as well as the new files...

Addendum 2 - man Windows sucks at removing zip files from zip files. I apologize for blaming TEPS for something that's a Windows problem.

**Comment by cczhu** [comment]
After much haranguing, I could consistently reproduce a TEPS bug where folders *I've placed in the Recycling Bin and then deleted* get included when TEPS produces a zip for TEPS-II. This literally blew my mind. I'm astonished this can happen, and vehemently refuse to try restarting my computer to see if it'll fix it.

Since "zip for TEPS-II" is literally just zipping up the `Emission` folder, I'll do that manually and will advise my future self to do so as well.

**Comment by cczhu** [comment]
Sent a zip file to Sean to run TEPs-II. He obtained:

![image](https://user-images.githubusercontent.com/442891/113163829-872cf500-920e-11eb-84ff-190b069cbd69.png)

vs. Arman's results using my TEPs-I output while generating new neural network training data:

![image](https://user-images.githubusercontent.com/442891/113163952-a62b8700-920e-11eb-8758-344ddce51cf4.png)

I'm not 100% certain why they aren't identical (since running our data through an NN in feedforward mode should be deterministic), but the differences are small enough that I can't bring myself to care 🤷‍♂️.

Since we've now confirmed we can obtain sensible eCO2 measures from TEPs, closing this issue.

**Comment by cczhu** [comment]
Turns out Sean sent over the wrong results. Here (from e-mail 2021-03-31) are his emissions calculations using the speeds Arman generated:

![image](https://user-images.githubusercontent.com/442891/113243747-9600bf80-9281-11eb-87aa-42c6e91a7b7f.png)

and his results using the speeds I generated:

![image](https://user-images.githubusercontent.com/442891/113243779-a6189f00-9281-11eb-870d-ef8b42967ac2.png)

They're identical, so case closed.
